Repository openimsdk/openim-sdk-core, pull requests merged in 2023-10, with the labels that each got.

#353 fix: upload logs error invalid memory address or nil pointer dereference
  internal/third/log.go
Labels: size/S

#357 fix: message unread count remove when user not in group.
  internal/conversation_msg/read_drawing.go
  pkg/db/conversation_model.go
Labels: size/L

#364 fix: when uploading logs, other ctrip writes caused upload failure
  internal/third/log.go
Labels: size/M

#361 fix: group member delete trigger and close ws conn when user logout.
  internal/conversation_msg/create_message.go
  internal/conversation_msg/message_check.go
  internal/group/group.go
  internal/interaction/long_conn_mgr.go
Labels: size/S

#360 Fix msgHandleByContentType, set msg.AdvancedTextElem.
  internal/conversation_msg/conversation_msg.go
Labels: size/XS

#379 fix: add avatar and nickname when sessionType is notification.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/sdk.go
  internal/user/sdk.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/user.go
  pkg/sdk_params_callback/conversation_msg_sdk_struct.go
  test/t_conversation_msg.go
  test/t_friend_sdk.go
  testv2/conversation_test.go
  testv2/user_test.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_group.go
Labels: size/L

#381 fix: firebase token and user status update.
  internal/cache/cache.go
  internal/cache/cahe.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sdk.go
  internal/conversation_msg/sync.go
  internal/full/full.go
  internal/group/notification.go
  internal/login/init_login.go
  internal/third/log.go
  internal/third/push.go
  internal/third/third.go
  internal/user/sdk.go
  internal/user/sync.go
  internal/user/user.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/third.go
  open_im_sdk_callback/callback_client.go
  pkg/constant/constant.go
  pkg/constant/server_api_router.go
  pkg/sdk_params_callback/conversation_msg_sdk_struct.go
  pkg/utils/utils.go
  sdk_struct/sdk_struct.go
  test/t_conversation_msg.go
  testv2/conversation_test.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/XL

#383 fix: trigger function change.
  internal/user/sync.go
Labels: size/XS

#384 fix: online status changed.
  internal/user/sync.go
Labels: size/XS

#385 fix: online status change.
  internal/user/sync.go
Labels: size/XS

#389 fix: file msg progress
  internal/conversation_msg/progress.go
  internal/conversation_msg/sdk.go
Labels: size/M

#392 fix: do not pull notifications when app reinstalled.
  internal/interaction/msg_sync.go
Labels: size/M

#393 fix: do not pull notifications when app reinstalled.
  internal/conversation_msg/conversation_msg.go
  internal/interaction/msg_sync.go
Labels: size/XS
