Repository openimsdk/openim-sdk-core, pull requests merged in 2023-08, with the labels that each got.

#187 test
  testv3new/pressure_test.go
  testv3new/register_test.go
Labels: size/S

#189 test
  start.bat
  testv3new/build.cmd
  testv3new/constant/constant.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_manager.go
  testv3new/start.bat
  testv3new/test_struct.go
  testv3new/testcore/config.go
Labels: size/M

#193 fix: can't compile
  internal/conversation_msg/progress.go
  open_im_sdk_callback/callback_client.go
Labels: size/S

#197 test: pressure test code
  internal/interaction/long_conn_mgr.go
  testv3new/cmd/main.go
  testv3new/config.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_test.go
  testv3new/test_struct.go
  testv3new/test_user_manager.go
  testv3new/testcore/lightweight.go
  testv3new/utils.go
Labels: size/XL

#199 fix bug: new conversation unreadcount
  cmd/main.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  pkg/db/conversation_model.go
  pkg/sdkerrs/code.go
  testv3/funcation/config.go
  testv3new/cmd/main.go
  testv3new/config.go
  testv3new/constant/constant.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_manager.go
  testv3new/register_test.go
  testv3new/test_user_manager.go
  testv3new/testcore/config.go
  testv3new/testcore/full.go
  testv3new/testcore/lightweight.go
  testv3new/utils.go
Labels: size/XL

#201 Fix: Program will crash when websocket just initialized and send message
  internal/interaction/long_conn_mgr.go
  internal/login/init_login.go
  open_im_sdk/init_login.go
Labels: size/S

#205 feat: server thumbnail
  internal/conversation_msg/sdk.go
Labels: size/M

#207 fix: group invited user synced all group members
  internal/group/notification.go
Labels: size/XS

#209 fix: group entry notification processing
  internal/group/notification.go
  testv2/config.go
  testv2/init.go
Labels: size/S

#211 fix: delete send failed msg
  internal/conversation_msg/delete.go
  pkg/sdkerrs/code.go
  pkg/sdkerrs/predefine.go
Labels: size/S

#214 old read msg status is not true
  internal/conversation_msg/conversation_msg.go
Labels: size/XS

#219 fix: js msg file ext
  internal/conversation_msg/sdk.go
Labels: size/S

#217 test: add function of create group and send messages
  internal/conversation_msg/sync.go
  internal/interaction/long_conn_mgr.go
  internal/util/post.go
  test/login.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/test_user_manager.go
  testv3new/testcore/lightweight.go
Labels: size/L

#224 feat: wasm add business listener
  wasm/event_listener/listener.go
  wasm/wasm_wrapper/wasm_init_login.go
Labels: size/S

#226 fix bug: clear empty conversation
  internal/conversation_msg/read_drawing.go
Labels: size/XS

#231 feat: batch sync users and groups
  cmd/main.go
  internal/cache/cache.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/sync.go
  internal/full/full_model.go
  internal/group/group.go
  test/config.go
  test/login.go
Labels: size/L

#233 new feat: Batch sync users and groups
  internal/cache/cache.go
  internal/group/group.go
Labels: size/M

#234 feat: log level can set gorm log level
  internal/file/upload_test.go
  internal/login/init_login.go
  pkg/db/db_init.go
  pkg/db/db_js.go
Labels: size/S

#235 Add feature 220
  go.mod
  go.sum
  internal/cache/cache.go
  internal/conversation_msg/conversation_notification.go
  internal/login/init_login.go
  internal/user/sdk.go
  internal/user/sync.go
  internal/user/user.go
  open_im_sdk/user.go
  open_im_sdk_callback/callback_client.go
  pkg/constant/constant.go
  pkg/constant/server_api_router.go
  test/t_friend_sdk.go
Labels: size/L

#238 fix bug: sync conversations may panic
  internal/login/init_login.go
Labels: size/XS

#245 fix bug: sync users
  internal/cache/cache.go
  internal/group/group.go
Labels: size/S

#240 add test for feature-220
  pkg/constant/server_api_router.go
  testv2/init.go
  testv2/user_test.go
  wasm/event_listener/listener.go
Labels: size/M

#246 fix: user goroutine did not exit when ws dial because of token invalid or expired
  internal/login/init_login.go
Labels: size/XS

#243 synchronization group member optimization
  internal/group/sync.go
  testv2/config.go
  testv2/group_test.go
  testv2/init.go
Labels: size/M

#248 fix: call panic stack
  open_im_sdk/util.go
Labels: size/XS

#252 fix: avoid panic when local don't have message
  internal/conversation_msg/message_check.go
  test/config.go
  testv3new/test_user_manager.go
Labels: size/S

#256 feat: pressure test and msg test
  msgtest/config.go
  msgtest/friend_manager.go
  msgtest/group_manager.go
  msgtest/msg_sender.go
  msgtest/pressure_test.go
  msgtest/pressure_tester.go
  msgtest/test_struct.go
  msgtest/user_manager.go
  msgtest/utils.go
  single_test/msg_delay_open_im.go
  single_test/online_open_im.go
  single_test/press_open_im.go
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/listener.go
  testv3/funcation/login.go
  testv3/funcation/sendmsg.go
  testv3/funcation/struct.go
  testv3/funcation/util.go
  testv3/login_test.go
  testv3/msg_test.go
  testv3/register_test.go
  testv3new/build.cmd
  testv3new/cmd/main.go
  testv3new/start.bat
  testv3new/testcore/listener.go
  work_group_test/create_work_group_open_im.go
  work_group_test/msg_delay_open_im.go
  work_group_test/press_open_im.go
Labels: size/XXL

#250 new feat: new con sync unread
  cmd/main.go
  go.mod
  go.sum
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sync.go
Labels: size/M

#260 fix: some messages seq is zero,filter this message and print exception info
  internal/conversation_msg/read_drawing.go
  pkg/db/chat_log_model_v3.go
Labels: size/S

#262 feat: test cicd
  .github/workflows/build-docker-image.yml
  .github/workflows/openimci.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  Makefile
  go.mod
  go.sum
  scripts/template/LICENSE
  scripts/template/footer.md.tmpl
  scripts/template/head.md.tmpl
Labels: size/XL

#263 fix: user online status pb change
  go.mod
  go.sum
  internal/user/sync.go
Labels: size/S

#264 Pressure test
  msgtest/config.go
  msgtest/module/msg_sender.go
  msgtest/module/user_manager.go
  msgtest/pressure_test.go
  msgtest/test_struct.go
Labels: size/L

#265 Optimize userid
  internal/user/sdk.go
  internal/user/user.go
  open_im_sdk/user.go
Labels: size/M

#266 Update Makefile
  Makefile
Labels: size/XS

#276 test: add sdk user statistics message
  cmd/gordon_main.go
  internal/conversation_msg/conversation_msg.go
  internal/interaction/long_conn_mgr.go
  msgtest/config.go
  msgtest/message_test.go
  msgtest/module/manager.go
  msgtest/sdk_user_simulator/listener.go
  msgtest/sdk_user_simulator/user.go
  pkg/constant/server_api_router.go
Labels: size/L

#283 refactor: Optimize cross-language passing parameters
  open_im_sdk/user.go
Labels: size/XS

#279 feat: Pressure test code
  msgtest/module/group_manager.go
  msgtest/module/user_manager.go
  msgtest/pressure_test.go
Labels: size/L

#286 fix: sdk remove group sync concurrent,maybe cause sync group members failed.
  internal/conversation_msg/conversation_notification.go
  internal/group/group.go
  internal/group/sync.go
  internal/interaction/long_conn_mgr.go
Labels: size/M

#289 private chat lock
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sdk.go
Labels: size/S

#290 fix: group icon update and private chat notification update
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/full/full.go
  internal/full/open_im_sdk_full.go
  internal/group/sync.go
  internal/login/init_login.go
  wasm/exec/executor.go
Labels: size/L

#299 chore: default thumbnail size
  internal/conversation_msg/sdk.go
Labels: size/XS
