Repository openimsdk/openim-sdk-core, pull requests merged in 2023-06, with the labels that each got.

#85 style: some details
  .vscode/launch.json
  Makefile
  go.mod
  go.sum
  internal/conversation_msg/create_message.go
  wasm/indexdb/group_member_model.go
Labels: size/M

#84 2 wasm
  go.sum
  wasm/indexdb/friend_model.go
Labels: size/S

#80 style: style adjustments
  .gitignore
  internal/cache/cache.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/max_seq_recorder.go
  internal/conversation_msg/message_controller.go
  internal/conversation_msg/progress.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sdk.go
  internal/conversation_msg/sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/long_connection.go
  internal/signaling/signaling.go
  internal/third/push.go
  open_im_sdk/file.go
  open_im_sdk_callback/callback_go_sdk.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  pkg/db/chat_log_model_v3.go
  pkg/db/model_struct/data_model_struct.go
  pkg/sdkerrs/code.go
  pkg/sdkerrs/error.go
  pkg/sdkerrs/predefine.go
  sdk_struct/sdk_struct.go
  testv2/empty_test.go
  testv2/sync_test.go
Labels: size/L

#83 style: some details
  go.sum
  pkg/db/black_model.go
  pkg/db/chat_log_model.go
  pkg/db/chat_log_model_v3.go
  pkg/db/conversation_model.go
  pkg/db/db_interface/databse.go
  testv2/config.go
  wasm/indexdb/black_model.go
  wasm/indexdb/chat_log_model.go
  wasm/indexdb/chat_log_reaction_extension_model.go
  wasm/indexdb/conversation_model.go
  wasm/indexdb/super_group_model.go
  wasm/indexdb/user_model.go
Labels: size/L

#87 feat: main test
  .gitignore
  internal/cache/cache.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/max_seq_recorder.go
  internal/conversation_msg/message_controller.go
  internal/conversation_msg/progress.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sdk.go
  internal/conversation_msg/sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/long_connection.go
  internal/signaling/signaling.go
  internal/third/push.go
  open_im_sdk/file.go
  open_im_sdk_callback/callback_go_sdk.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  pkg/db/chat_log_model_v3.go
  pkg/db/model_struct/data_model_struct.go
  pkg/sdkerrs/code.go
  pkg/sdkerrs/error.go
  pkg/sdkerrs/predefine.go
  sdk_struct/sdk_struct.go
  testv2/empty_test.go
  testv2/sync_test.go
Labels: size/L

#90 V3 send message
  go.sum
  internal/conversation_msg/sdk.go
Labels: size/S
