Repository openimsdk/openim-sdk-core, pull requests merged in 2023-07, with the labels that each got.

#93 230709 bantanger test
  testv2/init.go
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/friend.go
  testv3/funcation/reliability.go
  testv3/funcation/sendMessage.go
  testv3/funcation/util.go
  testv3/json_test.go
  testv3/msg_delay_test.go
  testv3/register_test.go
Labels: size/L

#95 feat: add test function about user login
  testv3/funcation/config.go
  testv3/funcation/friend.go
  testv3/funcation/login.go
  testv3/funcation/register.go
  testv3/funcation/reliability.go
  testv3/funcation/sendMessage.go
  testv3/login_test.go
  testv3/register_test.go
Labels: size/L

#96 Revert "feat: add test function about user login"
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/friend.go
  testv3/funcation/login.go
  testv3/funcation/reliability.go
  testv3/funcation/sendMessage.go
  testv3/login_test.go
  testv3/register_test.go
Labels: size/L

#100 feat: add test function about user send msg P2P and Group
  testv2/conversation_test.go
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/conversation.go
  testv3/funcation/listener.go
  testv3/funcation/login.go
  testv3/funcation/reliability.go
  testv3/funcation/sendMessage.go
  testv3/funcation/sendmsg.go
  testv3/funcation/struct.go
  testv3/login_test.go
  testv3/msg_delay_test.go
  testv3/msg_test.go
  testv3/register_test.go
Labels: size/XL

#104 feat: add test function about user sends messages to multiple sessions
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/listener.go
  testv3/funcation/login.go
  testv3/funcation/sendMessage.go
  testv3/funcation/sendmsg.go
  testv3/funcation/struct.go
  testv3/msg_test.go
  testv3/register_test.go
Labels: size/L

#108 feat: add wasm multipart upload
  .vscode/launch.json
  .vscode/settings.json
  internal/conversation_msg/file_js.go
  internal/conversation_msg/sdk.go
  internal/util/post.go
  pkg/db/db_js.go
  wasm/event_listener/caller.go
  wasm/exec/executor.go
  wasm/indexdb/black_model.go
  wasm/indexdb/cache_message.go
  wasm/indexdb/chat_log_model.go
  wasm/indexdb/chat_log_reaction_extension_model.go
  wasm/indexdb/conversation_model.go
  wasm/indexdb/conversation_unread_message_model.go
  wasm/indexdb/friend_model.go
  wasm/indexdb/friend_request_model.go
  wasm/indexdb/group_member_model.go
  wasm/indexdb/group_model.go
  wasm/indexdb/group_request.model.go
  wasm/indexdb/init.go
  wasm/indexdb/notification_model.go
  wasm/indexdb/super_group_chat_log_model.go
  wasm/indexdb/super_group_model.go
  wasm/indexdb/user_model.go
Labels: kind/feature

#109 fix bug: add friend sync both recv and send request
  internal/friend/friend.go
Labels: size/XS

#111 feat: add log changelog file
  CHANGELOG/.chglog/CHANGELOG.tpl.md
  CHANGELOG/.chglog/config.yml
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-2.0.md
  CHANGELOG/CHANGELOG-2.1.md
  CHANGELOG/CHANGELOG-2.2.md
  CHANGELOG/CHANGELOG-2.3.md
  CHANGELOG/CHANGELOG-2.9.md
  CHANGELOG/CHANGELOG-3.0.md
  CHANGELOG/CHANGELOG.md
  Makefile
  cmd/gordon_main.go
  cmd/main.go
  cmd/online_open_im.go
  cmd/parse.go
  cmd/press_open_im.go
  cmd/reliability_open_im.go
  cmd/sk_main.go
  test/t_group_sdk.go
Labels: size/XL

#130 fix: Makefile update for CI
  Makefile
Labels: size/XS

#132 Update README.md
  README.md
Labels: size/S

#134 fix: sync user info
  internal/user/sync.go
Labels: size/XS

#139 fix: error uploading the same hash file at the same time
  internal/file/upload.go
  internal/file/upload_test.go
Labels: size/L

#144 docs: add code owners
  .github/workflows/auto-invite.yml
  docs/.generated_docs
  docs/CODEOWNERS
  docs/contrib/cicd-actions.md
  docs/contrib/code_conventions.md
  docs/contrib/development.md
  docs/contrib/git_workflow.md
Labels: size/XL

#138 feat: add feature
  .github/.codecov.yml
  .github/labels.yml
  .github/workflows/auto-invite.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/check-coverage.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e-test.yml
  .github/workflows/gosec.yml
  .github/workflows/issue-robot.yml
  .github/workflows/link-pr.yml
  .github/workflows/opencommit.yml
  .github/workflows/openimci.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/sync.yml
  .golangci.yml
  .goreleaser.yaml
  CHANGELOG/.chglog/config.yml
  LICENSE_TEMPLATE
  Makefile
  cmd/parse.go
  go.mod
  go.sum
  internal/conversation_msg/delete.go
  internal/conversation_msg/max_seq_recorder.go
  internal/conversation_msg/message_controller.go
  internal/conversation_msg/progress.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sync.go
  internal/file/bitmap.go
  internal/file/file.go
  internal/file/file_default.go
  internal/file/file_js.go
  internal/file/md5.go
  internal/file/upload.go
  internal/file/upload_test.go
  internal/third/push.go
  open_im_sdk/file.go
  open_im_sdk_callback/callback_go_sdk.go
  pkg/db/chat_log_model_v3.go
  pkg/sdkerrs/code.go
  pkg/sdkerrs/error.go
  pkg/sdkerrs/predefine.go
  scripts/githooks/commit-msg
  scripts/githooks/pre-commit
  scripts/githooks/pre-push
  testv2/empty_test.go
  testv2/sync_test.go
  testv3/funcation/account.go
  testv3/funcation/conversation.go
  testv3/funcation/login.go
  testv3/funcation/reliability.go
  testv3/funcation/sendmsg.go
  testv3/funcation/struct.go
  testv3/funcation/util.go
  testv3/login_test.go
  testv3/msg_test.go
  testv3/register_test.go
  wasm/indexdb/notification_model.go
Labels: size/XXL

#155 fix: msg file Content-Type
  internal/conversation_msg/sdk.go
  pkg/content_type/content_type.go
Labels: size/L

#150 feat: add release
  .golangci.yml
  .goreleaser.yaml
Labels: size/XL

#131 test: add test function about 1000 users join group send msg (#124)
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/progress.go
  internal/group/sdk.go
  open_im_sdk/file.go
  pkg/constant/server_api_router.go
  testv2/group_test.go
  testv3/funcation/account.go
  testv3/funcation/config.go
  testv3/funcation/conversation.go
  testv3/funcation/listener.go
  testv3/funcation/login.go
  testv3/funcation/reliability.go
  testv3/funcation/sendMessage.go
  testv3/funcation/struct.go
  testv3/funcation/util.go
  testv3/msg_test.go
  testv3/register_test.go
  testv3new/cmd/main.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_manager.go
  testv3new/register_test.go
  testv3new/testcore/config.go
  testv3new/testcore/full.go
  testv3new/testcore/lightweight.go
  testv3new/testcore/listener.go
  wasm/indexdb/notification_model.go
Labels: size/XXL

#164 feat: add pressure_test
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_test.go
Labels: size/L

#152 fix: msg syncer sync msg has sync when old msg push
  internal/conversation_msg/delete.go
  internal/interaction/msg_sync.go
Labels: size/XS

#170 Fix: still reconn when token is invalid
  internal/login/init_login.go
  internal/login/sdk.go
Labels: size/S

#172 fix: ws conn token error and image parse
  go.mod
  go.sum
  internal/conversation_msg/image.go
  internal/conversation_msg/sdk.go
  internal/interaction/long_conn_mgr.go
  pkg/content_type/content_type.go
  testv3/funcation/util.go
  testv3new/cmd/main.go
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/register_manager.go
  testv3new/testcore/lightweight.go
Labels: size/L

#173 fix bug: wasm sql
  wasm/indexdb/friend_request_model.go
Labels: size/XS

#176 Fix: wasm close db
  internal/interaction/long_conn_mgr.go
  pkg/db/db_js.go
  testv2/group_test.go
  testv2/init.go
  testv2/sync_test.go
Labels: size/L

#177 fix: wasm db close
  internal/interaction/long_conn_mgr.go
  pkg/db/db_js.go
  testv2/group_test.go
  testv2/init.go
  testv2/sync_test.go
Labels: size/L

#178 test program
  build.cmd
  start.bat
  testv3new/pressure_test.go
  testv3new/pressure_tester.go
  testv3new/test_struct.go
Labels: size/L

#180 fix bug: user update faceURL and nickName not exist
  cmd/main.go
  internal/full/full.go
  internal/full/open_im_sdk_full.go
  internal/login/init_login.go
  pkg/db/db_interface/databse.go
  pkg/db/group_member_model.go
  pkg/utils/utils.go
  test/t_friend_sdk.go
Labels: size/L
