Repository openimsdk/openim-sdk-core, pull requests merged in 2023-11, with the labels that each got.

#396 feat: file read cache
  internal/file/file_default.go
  internal/file/file_js.go
  testv2/file_test.go
Labels: size/L

#400 refactor: change login mgr export path.
  internal/conversation_msg/sdk.go
  internal/login/init_login.go
  internal/login/sdk.go
  open_im_sdk/init_login.go
  open_im_sdk/userRelated.go
  test/sendMessage.go
  test/t_friend_sdk.go
  testv2/create_msg_test.go
Labels: size/XXL

#403 fix: large file signing timeout
  internal/file/file_test.go
  internal/file/upload.go
  internal/file/upload_test.go
  internal/util/post.go
  open_im_sdk/userRelated.go
  testv2/config.go
Labels: size/L

#404 fix: pull message unread count remove.
  internal/conversation_msg/create_message.go
  internal/interaction/msg_sync.go
  open_im_sdk/listener.go
  open_im_sdk/util.go
  pkg/common/check.go
  pkg/db/group_member_model.go
  pkg/db/super_group_chat_log_model.go
  wasm/cmd/main.go
  wasm/event_listener/caller.go
  wasm/exec/executor.go
  wasm/wasm_wrapper/wasm_init_login.go
Labels: size/L

#405 fix: pull message unread count remove.
  internal/interaction/msg_sync.go
Labels: size/XS

#410 fix: search message sort and bug fix.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/sdk.go
  pkg/sdk_params_callback/conversation_msg_sdk_struct.go
Labels: size/M

#412 fix: search message sort and bug fix.
  internal/conversation_msg/conversation.go
Labels: size/S

#406 Update head.md.tmpl
  scripts/template/head.md.tmpl
Labels: size/XS

#415 fix: wasm createLocationMessage support float64 and trigger OnRecvOff…
  internal/conversation_msg/conversation_msg.go
  internal/interaction/long_conn_mgr.go
  wasm/event_listener/caller.go
Labels: size/M

#416 Bug/fix offline recv message
  internal/conversation_msg/conversation_msg.go
  internal/interaction/long_conn_mgr.go
Labels: size/S

#419 fix: add picture and video search.
  internal/conversation_msg/conversation.go
Labels: size/XS
