Repository openimsdk/openim-sdk-core, pull requests merged in 2023-12, with the labels that each got.

#426 fix: listener add empty implement avoid panic.
  internal/business/open_im_sdk_business.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sdk.go
  internal/friend/friend.go
  internal/group/group.go
  internal/interaction/msg_sync.go
  open_im_sdk/caller.go
  open_im_sdk/em.go
  open_im_sdk/listener.go
  open_im_sdk/userRelated.go
  testv2/init.go
Labels: size/XL

#427 fix: listener add empty implement avoid panic.
  internal/business/business.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/friend/friend.go
  internal/group/group.go
  internal/group/notification.go
  internal/user/user.go
  open_im_sdk/userRelated.go
Labels: size/M

#428 refactor: using closures, can allow the listener to be overridden mul…
  internal/business/open_im_sdk_business.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/sdk.go
  internal/friend/friend.go
  internal/group/group.go
  internal/user/user.go
  open_im_sdk/caller.go
  open_im_sdk/userRelated.go
Labels: size/L

#429 refactor: using closures, can allow the listener to be overridden multiple times.
  internal/business/business.go
  internal/business/open_im_sdk_business.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sdk.go
  internal/friend/friend.go
  internal/group/group.go
  internal/group/notification.go
  internal/group/sync.go
  internal/user/sync.go
  internal/user/user.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_go_sdk.go
Labels: size/L

#431 feat: token callback and upload log
  internal/interaction/long_conn_mgr.go
  internal/third/log.go
  internal/third/log_test.go
  internal/third/progress.go
  internal/third/third.go
  internal/third/zip.go
  internal/util/post.go
  open_im_sdk/apicb.go
  open_im_sdk/third.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_client.go
  pkg/ccontext/context.go
  sdk_struct/sdk_struct.go
Labels: size/L

#432 feat: token callback
  open_im_sdk/apicb.go
  open_im_sdk/userRelated.go
Labels: size/XS

#437 fix: ConversationInfo.latestMsg.isRead & status not synchronized
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/read_drawing.go
  internal/interaction/long_conn_mgr.go
  open_im_sdk/userRelated.go
Labels: size/M

#436 add pin friend
  cmd/gordon_main.go
  go.mod
  go.sum
  internal/conversation_msg/sdk.go
  internal/friend/conversion.go
  internal/friend/friend.go
  internal/friend/sdk.go
  internal/user/sync.go
  internal/user/user.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/em.go
  open_im_sdk/friend.go
  open_im_sdk_callback/callback_client.go
  open_im_sdk_callback/callback_go_sdk.go
  pkg/constant/constant.go
  pkg/constant/server_api_router.go
  pkg/db/conversation_model.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/friend_model.go
  pkg/db/model_struct/data_model_struct.go
  pkg/sdk_params_callback/friend_sdk_struct.go
  test/t_friend_sdk.go
  testv2/config.go
  testv2/friend_test.go
  testv2/init.go
  wasm/event_listener/listener.go
  wasm/indexdb/friend_model.go
  wasm/indexdb/temp_struct/struct.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
  wasm/wasm_wrapper/wasm_friend.go
Labels: size/L

#443 fix: conversation's latestMsg struct unmarshal err type.
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/read_drawing.go
  open_im_sdk/userRelated.go
Labels: size/S

#442 Add set ex friend, conversation, and userinfo. Add search conversation
  go.mod
  go.sum
  identifier.sqlite
  internal/conversation_msg/sdk.go
  internal/friend/friend.go
  internal/friend/sdk.go
  internal/group/sdk.go
  internal/user/sdk.go
  internal/user/user.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/em.go
  open_im_sdk/friend.go
  open_im_sdk/group.go
  open_im_sdk/user.go
  open_im_sdk_callback/callback_client.go
  open_im_sdk_callback/callback_go_sdk.go
  pkg/constant/server_api_router.go
  pkg/db/conversation_model.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/friend_model.go
  test/t_friend_sdk.go
  test/t_group_sdk.go
  testv2/config.go
  testv2/conversation_test.go
  testv2/friend_test.go
  testv2/group_test.go
  testv2/init.go
  testv2/user_test.go
  wasm/cmd/main.go
  wasm/event_listener/listener.go
  wasm/indexdb/conversation_model.go
  wasm/indexdb/friend_model.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
  wasm/wasm_wrapper/wasm_friend.go
  wasm/wasm_wrapper/wasm_user.go
Labels: size/L

#447 Add update friend info notification
  go.mod
  go.sum
  internal/friend/friend.go
  internal/util/post.go
  pkg/constant/constant.go
  pkg/syncer/syncer.go
Labels: size/L

#449 fix: remove pointer avoid panic.
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/read_drawing.go
  open_im_sdk/userRelated.go
  pkg/utils/utils.go
  ws_wrapper/cmd/Makefile
  ws_wrapper/cmd/open_im_sdk_electron.go
  ws_wrapper/cmd/open_im_sdk_my.go
  ws_wrapper/cmd/open_im_sdk_server.go
  ws_wrapper/test/client/client.go
  ws_wrapper/test/cmd/main.go
  ws_wrapper/test/simulationClient.go
  ws_wrapper/utils/platform_number_id_to_name.go
  ws_wrapper/utils/strings.go
  ws_wrapper/ws_local_server/constant.go
  ws_wrapper/ws_local_server/handle_func.go
  ws_wrapper/ws_local_server/ws_conversation_msg.go
  ws_wrapper/ws_local_server/ws_friend.go
  ws_wrapper/ws_local_server/ws_group.go
  ws_wrapper/ws_local_server/ws_handle.go
  ws_wrapper/ws_local_server/ws_init_login.go
  ws_wrapper/ws_local_server/ws_organization.go
  ws_wrapper/ws_local_server/ws_server.go
  ws_wrapper/ws_local_server/ws_signaling.go
  ws_wrapper/ws_local_server/ws_user.go
  ws_wrapper/ws_local_server/ws_work_moments.go
Labels: size/XXL

#451 update log
  cmd/gordon_main.go
  cmd/press_open_im.go
  cmd/reliability_open_im.go
  cmd/sk_main.go
  go.mod
  go.sum
  msgtest/module/api_msg_sender.go
  pkg/log/file_line_hk.go
  pkg/log/log.go
  test/account.go
  test/login.go
  test/reliability.go
  test/sendMessage.go
  test/t_conversation_msg.go
  test/t_friend_sdk.go
  test/t_group_sdk.go
  test/work_group_create.go
Labels: size/XL

#457 fix: add re conn strategy and fix login slow when app has many conver…
  internal/interaction/long_conn_mgr.go
  internal/interaction/reconnect.go
  pkg/db/chat_log_model_v3.go
  pkg/db/db_init.go
Labels: size/L

#459 fix: add re conn index increment.
  internal/interaction/reconnect.go
Labels: size/XS

#456 Add comment
  internal/conversation_msg/conversation.go
  pkg/db/chat_log_model_v3.go
Labels: size/M
