Repository openimsdk/openim-sdk-core, pull requests merged in 2023-09, with the labels that each got.

#301 fix:The sdk about subscribing to online status in wasm is missing
  wasm/wasm_wrapper/wasm_user.go
  ws_wrapper/ws_local_server/ws_user.go
Labels: size/M

#305 fix: pull messages and notifications by paging.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sdk.go
  internal/interaction/msg_sync.go
Labels: size/M

#307 fix: pull notifications by paging.
  internal/interaction/msg_sync.go
  wasm/cmd/main.go
Labels: size/M

#308 fix: page pull notification.
  internal/interaction/msg_sync.go
Labels: size/XS

#309 fix: message update latest icon and name when first sync message.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
Labels: size/S

#310 fix: message update latest icon and name when first sync message.
  internal/conversation_msg/message_check.go
Labels: size/XS

#311 fix: message update latest icon and name when first sync message.
  internal/conversation_msg/message_check.go
Labels: size/XS

#306 feat:Caching of personal information of strangers in group chats
  internal/full/open_im_sdk_full.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/model_struct/data_model_struct.go
  pkg/db/stranger_model.go
  pkg/server_api_params/public_struct.go
  wasm/indexdb/init.go
  wasm/indexdb/stranger_model.go
Labels: size/L

#313 fix: stranger user model add wasm set func.
  internal/full/open_im_sdk_full.go
  open_im_sdk/user.go
  pkg/db/db_js.go
  wasm/cmd/main.go
  wasm/indexdb/stranger_model.go
  wasm/wasm_wrapper/wasm_user.go
Labels: size/S

#312 feat: add build js for #304
  pkg/db/stranger_model.go
Labels: size/S

#318 fix:Normal storage of stranger information
  open_im_sdk/user.go
  pkg/db/stranger_model.go
  wasm/indexdb/user_model.go
Labels: size/M

#316 feat: set openim sdk version
  Makefile
  docs/.generated_docs
  pkg/version/README.md
  pkg/version/base.go
  pkg/version/helpers.go
  pkg/version/helpers_test.go
  pkg/version/types.go
  pkg/version/version.go
Labels: size/L

#319 fix: remove stranger func in user model.
  msgtest/module/group_manager.go
  msgtest/pressure_test.go
  wasm/indexdb/stranger_model.go
  wasm/indexdb/user_model.go
Labels: size/M

#323 fix:When the network is disconnected, if the stranger’s personal information is returned to be empty, go to the local to get it, and no error will be thrown.
  internal/full/open_im_sdk_full.go
  open_im_sdk/user.go
  wasm/indexdb/stranger_model.go
Labels: size/S

#328 fix: repeated trigger conversation changed.
  internal/conversation_msg/conversation_msg.go
Labels: size/XS

#338 fix: unread bug fix when app reinstall.
  internal/conversation_msg/conversation_msg.go
Labels: size/XS

#340 feat: addlog
  go.mod
  go.sum
  internal/group/sdk.go
  internal/login/init_login.go
  internal/third/log.go
  internal/third/log_test.go
  internal/third/push.go
  open_im_sdk/third.go
  pkg/ccontext/context.go
  pkg/ccontext/context_test.go
  pkg/constant/server_api_router.go
  pkg/sdk_params_callback/third_sdk_struct.go
Labels: size/L
