Repository openimsdk/openim-sdk-core, pull requests merged in 2024-09, with the labels that each got.

#682 feat: implement resource manager tool.
  open_im_sdk_callback/callback_client.go
  pkg/utils/lock_pool.go
Labels: size/M

#684 refactor: performance optimization of pull messages.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
Labels: size/L

#685 fix: solve AddFriend uncorrect call.
  internal/friend/sdk.go
  internal/friend/sync.go
Labels: size/S

#686 feat: update set GroupInfo logic.
  go.mod
  go.sum
  internal/group/sdk.go
  pkg/constant/server_api_router.go
Labels: size/S

#688 refactor: performance optimization of pull messages.
  go.mod
  go.sum
  internal/conversation_msg/message_check.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  pkg/constant/constant.go
Labels: size/M

#687 feat: implement batchNewMessages method.
  internal/conversation_msg/conversation_msg.go
  open_im_sdk/em.go
Labels: size/M

#689 refactor: performance optimization of pull messages.
  internal/interaction/long_conn_mgr.go
Labels: size/XS

#690 refactor: performance optimization of pull messages.
  internal/conversation_msg/message_check.go
Labels: size/XS

#695 fix: cmd panic and remove struct.
  internal/interaction/msg_sync.go
  internal/util/post.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  sdk_struct/sdk_struct.go
Labels: size/S

#699 Test feat
  .DS_Store
  go.mod
  go.sum
  integration_test/internal/checker/conversation.go
  integration_test/internal/checker/counter.go
  integration_test/internal/checker/group.go
  integration_test/internal/checker/msg.go
  integration_test/internal/checker/relation.go
  integration_test/internal/checker/user.go
  integration_test/internal/config/config.go
  integration_test/internal/config/limit.go
  integration_test/internal/manager/group_manager.go
  integration_test/internal/manager/msg_manager.go
  integration_test/internal/manager/relation_manager.go
  integration_test/internal/manager/user_manager.go
  integration_test/internal/pkg/decorator/log.go
  integration_test/internal/pkg/initialization/flag.go
  integration_test/internal/pkg/initialization/global.go
  integration_test/internal/pkg/initialization/sdk.go
  integration_test/internal/pkg/progress/ansi.go
  integration_test/internal/pkg/progress/api.go
  integration_test/internal/pkg/progress/bar.go
  integration_test/internal/pkg/progress/progress.go
  integration_test/internal/pkg/sdk_user_simulator/listener.go
  integration_test/internal/pkg/sdk_user_simulator/user.go
  integration_test/internal/pkg/utils/progress.go
  integration_test/internal/pkg/utils/user.go
  integration_test/internal/process/task.go
  integration_test/internal/sdk/group.go
  integration_test/internal/sdk/msg.go
  integration_test/internal/statistics/msg.go
  integration_test/internal/vars/cmd.go
  integration_test/internal/vars/msg.go
  integration_test/internal/vars/os.go
  integration_test/internal/vars/user.go
  integration_test/main.go
  internal/conversation_msg/message_check.go
  internal/group/group.go
  internal/group/notification.go
  internal/group/sdk.go
  internal/interaction/long_conn_mgr.go
  internal/util/post.go
  msgtest/config.go
  msgtest/main/main.go
  msgtest/module/pressure.go
  msgtest/module/user_manager.go
  msgtest/sdk_user_simulator/user.go
  open_im_sdk/caller.go
  open_im_sdk/init_login.go
  open_im_sdk/userRelated.go
  pkg/db/conversation_model.go
  pkg/db/db_init.go
  testv2/group_test.go
  testv2/init.go
  testv2/third_test.go
Labels: size/XXL

#700 refactor: mv GetConversationsHasReadAndMaxSeq from HTTP to Websocket.
  internal/conversation_msg/sync.go
  pkg/constant/constant.go
  pkg/db/db_init.go
Labels: size/S

#701 fix: ws read max seq error.
  internal/interaction/long_conn_mgr.go
Labels: size/XS

#704 refactor: fix error handling in SendMessage function
  internal/conversation_msg/api.go
  pkg/constant/constant.go
  pkg/db/conversation_model.go
Labels: size/XS

#707 Refactor: Remove unused GetUsersInfoWithCache function
  Makefile
  open_im_sdk/user.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_user.go
Labels: size/S

#710 fix: IncrSyncGroupAndMember error
  internal/group/incremental_sync.go
  pkg/db/version_sync.go
Labels: size/XS

#709 refactor: update setGroupInfoEx field.
  go.mod
  go.sum
  internal/group/api.go
  internal/group/server_api.go
  pkg/api/api.go
  test/group_test.go
Labels: size/S

#711 fix: udpate setGroupInfo fields.
  go.mod
  go.sum
  internal/group/api.go
  test/group_test.go
Labels: size/S

#714 refactor: Exclude files and directories from non-English comment check
  .github/workflows/comment-check.yml
Labels: size/L

#712 feat: test Workflow
  .github/workflows/go-build-test.yml
  integration_test/internal/checker/counter.go
  integration_test/internal/config/limit.go
  integration_test/main.go
Labels: size/L

#723 feat: cmd2value add call information
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/notification.go
  internal/conversation_msg/read_drawing.go
  open_im_sdk/file.go
  open_im_sdk/third.go
  open_im_sdk/userRelated.go
  pkg/common/cmd.go
  pkg/common/trigger_channel.go
Labels: size/L

#721 feat: implement update version file on release.
  .github/workflows/update-version-file-on-release.yml
Labels: size/M

#719 feat: change level del request
  internal/group/group.go
  internal/group/notification.go
Labels: size/S

#724 feat: add SearchConversation WASM
  internal/conversation_msg/notification.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/XS

#725 test: fix get user token
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/user_manager.go
  msgtest/module/manager.go
  pkg/api/api.go
  test/init.go
Labels: size/S

#726 test: fix get user token
  integration_test/internal/manager/user_manager.go
Labels: size/XS

#727 refactor: update userToken to getAdminToken
  go.mod
  go.sum
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/user_manager.go
  msgtest/module/manager.go
  msgtest/module/user_manager.go
  pkg/api/api.go
  test/init.go
Labels: size/M

#728 refactor: change log and avoid nil array.
  README.md
  internal/conversation_msg/api.go
  internal/conversation_msg/notification.go
  pkg/common/cmd.go
  pkg/datafetcher/datafetcher.go
Labels: size/S
