Repository openimsdk/openim-sdk-core, pull requests merged in 2024-12, with the labels that each got.

#805 fix: get reverse history message change.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/message_check_test.go
Labels: size/L

#810 fix: go mod dep repo update and fix reverse fetch message duplicate.
  go.mod
  go.sum
  internal/conversation_msg/message_check.go
Labels: size/S

#813 fix: add server isEnd determination criteria for message retrieval.
  go.mod
  go.sum
  internal/conversation_msg/conversation.go
  internal/conversation_msg/message_check.go
  internal/third/log.go
  pkg/cache/cache.go
  pkg/db/version_sync.go
Labels: size/L

#812 fix: add server isEnd determination criteria for message retrieval.
  go.mod
  go.sum
  internal/conversation_msg/conversation.go
  internal/conversation_msg/message_check.go
  pkg/cache/cache.go
Labels: size/L

#814 fix: login user's info maybe empty when app reinstall.
  internal/conversation_msg/api.go
  internal/conversation_msg/message_check.go
  internal/user/api.go
  internal/user/user.go
  pkg/cache/manager.go
Labels: size/L

#815 fix: add server isEnd determination criteria for message retrieval.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/message_check.go
Labels: size/S

#816 fix: login user's info maybe empty when app reinstall.
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/message_check.go
  internal/user/api.go
  internal/user/user.go
  pkg/cache/manager.go
Labels: size/L

#819 fix: search message do not filter voice message when keyword is empty.
  internal/conversation_msg/conversation.go
Labels: size/XS

#820 fix: search message do not filter voice message when keyword is empty.
  internal/conversation_msg/conversation.go
Labels: size/XS

#822 fix: Add black api add lock
  internal/relation/api.go
Labels: size/XS

#824 fix: cicd notification.yml changed
  .github/workflows/go-build-test.yml
Labels: size/XS

#826 fix: quote message change to revoke message when app from background …
  internal/conversation_msg/api.go
  internal/conversation_msg/conversion.go
  internal/conversation_msg/message_check.go
Labels: size/S

#825 fix: quote message change to revoke message when app from background …
  internal/conversation_msg/api.go
  internal/conversation_msg/conversion.go
  internal/conversation_msg/message_check.go
Labels: size/S

#828 feat: add a function to quickly retrieve the context messages for a given message.
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
  internal/user/user.go
  open_im_sdk/conversation_msg.go
  pkg/cache/conversation_seq_cache.go
  pkg/cache/user_cache.go
  pkg/sdk_params_callback/conversation_msg_sdk_struct.go
  pkg/sdkerrs/code.go
  pkg/sdkerrs/predefine.go
  test/create_msg_test.go
Labels: size/L
