Repository openimsdk/openim-sdk-core, pull requests merged in 2024-11, with the labels that each got.

#767 fix: GetGroupMembersInfoFunc return key
  internal/group/cache.go
Labels: size/XS

#766 fix: Change check reinstall logic
  internal/interaction/msg_sync.go
  pkg/db/model_struct/data_model_struct.go
Labels: size/M

#770 feat: support stream message
  go.mod
  go.sum
  integration_test/internal/pkg/sdk_user_simulator/listener.go
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/notification.go
  internal/conversation_msg/server_api.go
  internal/conversation_msg/stream_msg.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/em.go
  open_im_sdk_callback/callback_client.go
  pkg/api/api.go
  sdk_struct/sdk_struct.go
  test/listener.go
  wasm/event_listener/listener.go
Labels: size/L

#771 fix: deleting the last message in a conversation will prompt failure
  wasm/indexdb/chat_log_model.go
Labels: size/XS

#773 fix: the bug where isEnd for fetching message history is not working correctly.
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversion.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/message_check_test.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/stream_msg.go
  pkg/db/chat_log_model.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/model_struct/data_model_struct.go
  pkg/db/temp_cache_chat_log_model.go
  pkg/sdk_params_callback/conversation_msg_sdk_struct.go
  sdk_struct/sdk_struct.go
  wasm/indexdb/cache_message.go
  wasm/indexdb/chat_log_model.go
  wasm/indexdb/init.go
Labels: size/XXL

#777 fix: solve uncorrect log in revoke handle.
  internal/conversation_msg/revoke.go
Labels: size/XS

#734 refactor: improve createMessage and sendMessage interface.
  .gitignore
  internal/conversation_msg/api.go
  internal/conversation_msg/create_message.go
  open_im_sdk/conversation_msg.go
  pkg/ccontext/context.go
  test/conversation_test.go
  test/create_msg_test.go
  test/init.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/XL, Breaking Change

#729 refactor: remove batchListener.
  internal/conversation_msg/conversation_msg.go
  open_im_sdk/em.go
  open_im_sdk/listener.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_client.go
  wasm/event_listener/listener.go
  wasm/wasm_wrapper/wasm_init_login.go
Labels: size/M, Breaking Change

#780 fix: remove unused contents.
  internal/conversation_msg/conversion.go
  internal/conversation_msg/stream_msg.go
  sdk_struct/sdk_struct.go
Labels: size/L

#784 fix: solve uncorrect delete temp file.
  internal/conversation_msg/api.go
Labels: size/S

#782 build: remove uncorrect schedule.
  .github/workflows/merge-from-milestone.yml
Labels: size/XS

#788 build: add bot PR merged filter.
  tools/changelog/changelog.go
Labels: size/XS

#789 Fix：Change check reinstall logic
  internal/interaction/msg_sync.go
Labels: size/S

#793 fix: create index failed when table name has `-`.
  pkg/db/chat_log_model.go
Labels: size/XS

#796 build: update PR body.
  .github/workflows/merge-from-milestone.yml
  .github/workflows/release.yml
Labels: size/XS

#801 fix: change the table name and add escaping.
  pkg/db/chat_log_model.go
Labels: size/XS

#800 fix: change errs to custom errs avoid sdk panic.
  internal/interaction/msg_sync.go
Labels: size/XS
