Repository openimsdk/openim-sdk-core, pull requests merged in 2024-08, with the labels that each got.

#632 bump: update go mod dependency version to latest.
  go.mod
  go.sum
Labels: size/S

#634 fix: accept or refuse group application remove lock.
  internal/group/notification.go
Labels: size/L

#633 bump: update go mod dependency version to latest. (#632)
  go.mod
  go.sum
  internal/group/notification.go
Labels: size/L

#635 fix: solve get list is nil when batch fetch.
  pkg/datafetcher/datafetcher.go
Labels: size/XS

#636 fix: filter Invalid.
  internal/group/sdk.go
Labels: size/XS

#639 deps: update bug-report.yaml
  .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/link-pr.yml
Labels: size/M

#640 deps: move yaml locate.
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: size/M

#641 feat: update issue template in sdk core.
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/rfc.md
Labels: size/L

#642 build(deps): update translator.yml
  .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/issue-robot.yml
  .github/workflows/issue-translator.yml
Labels: size/L

#648 Refactor: reconstruct issue and label in GitHub.
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/remove-unused-labels.yml
  .github/workflows/reopen-issue.yml
  .github/workflows/stale.yml
Labels: size/L

#649 fix: update uncorrect workflow.
  .github/workflows/reopen-issue.yml
Labels: size/S

#651 fix: remove env.
  .github/workflows/openimci.yml
Labels: size/S

#654 fix: remove unused release files.
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/link-pr.yml
  .github/workflows/opencommit.yml
  .github/workflows/openimci.yml
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: size/L

#629 feat send message
  go.mod
  go.sum
  integration_test/internal/checker/common.go
  integration_test/internal/checker/conversation.go
  integration_test/internal/checker/counter.go
  integration_test/internal/checker/group.go
  integration_test/internal/checker/msg.go
  integration_test/internal/checker/relation.go
  integration_test/internal/checker/user.go
  integration_test/internal/config/config.go
  integration_test/internal/config/limit.go
  integration_test/internal/config/statistics.go
  integration_test/internal/manager/file_manager.go
  integration_test/internal/manager/group_manager.go
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/msg_manager.go
  integration_test/internal/manager/relation_manager.go
  integration_test/internal/manager/user_manager.go
  integration_test/internal/pkg/decorator/log.go
  integration_test/internal/pkg/decorator/log_test.go
  integration_test/internal/pkg/initialization/flag.go
  integration_test/internal/pkg/initialization/global.go
  integration_test/internal/pkg/initialization/log.go
  integration_test/internal/pkg/initialization/sdk.go
  integration_test/internal/pkg/reerrgroup/errgroup.go
  integration_test/internal/pkg/sdk_user_simulator/listener.go
  integration_test/internal/pkg/sdk_user_simulator/user.go
  integration_test/internal/pkg/utils/context.go
  integration_test/internal/pkg/utils/err_test.go
  integration_test/internal/pkg/utils/error.go
  integration_test/internal/pkg/utils/progress.go
  integration_test/internal/process/checker/group.go
  integration_test/internal/process/checker/model.go
  integration_test/internal/process/process.go
  integration_test/internal/process/process_helper.go
  integration_test/internal/process/task.go
  integration_test/internal/process/v1.go
  integration_test/internal/sdk/conversation.go
  integration_test/internal/sdk/group.go
  integration_test/internal/sdk/msg.go
  integration_test/internal/sdk/relation.go
  integration_test/internal/statistics/msg.go
  integration_test/internal/vars/cmd.go
  integration_test/internal/vars/msg.go
  integration_test/internal/vars/user.go
  integration_test/main.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/sdk.go
  internal/flagconst/flag.go
  internal/group/notification.go
  internal/util/post.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  pkg/db/db_init.go
  testv2/config.go
  testv2/third_test.go
Labels: size/XXL

#658 feat: change lock to global db lock
  pkg/db/admin_group_request_model.go
  pkg/db/black_model.go
  pkg/db/chat_log_model.go
  pkg/db/chat_log_reaction_extension_model.go
  pkg/db/conversation_model.go
  pkg/db/db_init.go
  pkg/db/err_chat_log_model.go
  pkg/db/friend_model.go
  pkg/db/friend_request_model.go
  pkg/db/group_member_model.go
  pkg/db/group_model.go
  pkg/db/group_request_model.go
  pkg/db/notification_model.go
  pkg/db/sending_messages_model.go
  pkg/db/seq_data_model.go
  pkg/db/stranger_model.go
  pkg/db/super_group_chat_log_model.go
  pkg/db/super_group_model.go
  pkg/db/table_master.go
  pkg/db/temp_cache_chat_log_model.go
  pkg/db/upload_model.go
  pkg/db/user_command.go
  pkg/db/user_model.go
  pkg/db/version_sync.go
Labels: size/XL

#657 feat: implement log interface.
  .github/labels.yml
  .github/workflows/auto-invite-comment.yml
  .github/workflows/auto-invite.yml
  .github/workflows/check-coverage.yml
  .github/workflows/release.yml
  .github/workflows/reopen-issue.yml
  internal/third/log.go
  internal/util/sdklog/sdk_log.go
  open_im_sdk/third.go
Labels: size/XL

#661 fix: update interface func.
  go.mod
  internal/third/log.go
  open_im_sdk/third.go
Labels: size/XS

#663 fix: remove the conversation trigger to prevent waiting in a circular…
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/message_controller.go
Labels: size/L

#665 Feat test
  go.mod
  go.sum
  integration_test/internal/manager/msg_manager.go
  integration_test/internal/vars/user.go
  pkg/db/conversation_model.go
  pkg/db/super_group_chat_log_model.go
Labels: size/S

#664 fix: remove redundant func.
  internal/incrversion/option.go
Labels: size/M

#666 feat: implement panic recovery.
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
Labels: size/M

#667 feat: implment SDK log interface.
  .DS_Store
  go.mod
  go.sum
  integration_test/internal/pkg/initialization/log.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  internal/third/log.go
  internal/util/sdklog/sdk_log.go
  msgtest/main/main.go
  msgtest/sdk_user_simulator/user.go
  open_im_sdk/init_login.go
  open_im_sdk/third.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  test/account.go
  testv2/config.go
  testv2/third_test.go
Labels: size/L

#669 fix: optimize delete msg local logic.
  internal/conversation_msg/delete.go
  test/t_conversation_msg.go
  testv2/conversation_test.go
  testv2/init.go
Labels: size/M

#672 fix: fixed revoke burnMessage panic.
  internal/conversation_msg/revoke.go
  internal/interaction/long_conn_mgr.go
  wasm/event_listener/caller.go
Labels: size/M

#674 fix: the crash caused by calling log when sdk is not logged in
  open_im_sdk/third.go
  pkg/db/db_init.go
Labels: size/XS

#675 fix: update Logs interface.
  go.mod
  go.sum
  internal/conversation_msg/revoke.go
Labels: size/S

#677 fix: Bug fix for clearing unread messages.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/sync.go
  internal/interaction/msg_sync.go
  pkg/common/trigger_channel.go
  pkg/db/model_struct/data_model_struct.go
Labels: size/L
