Repository openimsdk/openim-sdk-core, pull requests merged in 2024-10, with the labels that each got.

#731 fix: val
  go.mod
  go.sum
  internal/user/user.go
Labels: size/XS

#737 fix: SearchLocalMessages no such table
  internal/conversation_msg/conversation.go
  test/config.go
  test/conversation_test.go
  test/init.go
Labels: size/M

#741 feat: Support FetchSurroundingMessages
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/entering.go
  open_im_sdk/conversation_msg.go
  test/create_msg_test.go
  test/init.go
  test/listener.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/L

#750 fix: remove version space
  version/version.go
Labels: size/S

#752 fix: update the latest message when group member's changed.
  internal/conversation_msg/notification.go
  internal/conversation_msg/read_drawing.go
  internal/group/group.go
  internal/relation/relation.go
  pkg/constant/constant.go
Labels: size/L

#747 fix: remove duplicate License.
  Makefile
  integration_test/internal/pkg/reerrgroup/errgroup.go
  wasm/cmd/static/wasm_exec.js
Labels: size/S

#743 feat: mark all conversation as read
  internal/conversation_msg/api.go
  open_im_sdk/conversation_msg.go
  pkg/db/conversation_model.go
  pkg/db/db_interface/databse.go
  test/config.go
  test/conversation_test.go
  wasm/cmd/main.go
  wasm/indexdb/conversation_model.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/M

#755 feat: implement default logger when no init.
  go.mod
  go.sum
Labels: size/S

#754 fix: After being removed as a group admin, delete group requests
  internal/group/notification.go
Labels: size/XS

#748 build: implement changelog generate.
  .github/workflows/changelog.yml
  .gitignore
  .goreleaser.yaml
  CHANGELOG/.chglog/CHANGELOG.tpl.md
  CHANGELOG/.chglog/config.yml
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-2.0.md
  CHANGELOG/CHANGELOG-2.1.md
  CHANGELOG/CHANGELOG-2.2.md
  CHANGELOG/CHANGELOG-2.3.md
  CHANGELOG/CHANGELOG-2.9.md
  CHANGELOG/CHANGELOG-3.0.md
  docs/CHANGELOG.md
  tools/changelog/changelog.go
Labels: size/XL

#746 build: implement create Pre-release PR from Milestone.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  .github/workflows/merge-from-milestone.yml
Labels: size/L

#733 feat: implement error stack print.
  go.mod
  go.sum
  open_im_sdk/caller.go
Labels: size/L

#756 fix: improve batchUserFaceURLandName logic.
  internal/conversation_msg/conversation_msg.go
  internal/user/api.go
  internal/user/full_sync.go
Labels: size/M

#762 fix: escape table names to avoid the sqlite error: near "-": syntax e…
  pkg/db/chat_log_model.go
Labels: size/XS

#765 Fix local cache: user cache and group member cache
  go.mod
  internal/conversation_msg/message_check.go
  internal/group/cache.go
  internal/group/group.go
  internal/relation/relation.go
  internal/relation/sync.go
  internal/user/user.go
  pkg/db/group_member_model.go
  test/long_conn_test.go
Labels: size/M

#764 fix: fix temp file don't remove when upload file.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  internal/conversation_msg/api.go
Labels: size/M
