Repository openimsdk/openim-sdk-core, pull requests merged in 2024-01, with the labels that each got.

#463 feat: support conversation input status and wasm websocket message returns the connection status
  go.mod
  go.sum
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/entering.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/ws_js.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/apicb.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/em.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_client.go
  pkg/constant/constant.go
  sdk_struct/sdk_struct.go
  test/t_friend_sdk.go
  testv2/config.go
  testv2/empty_test.go
  testv2/init.go
  wasm/cmd/main.go
  wasm/event_listener/listener.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/L

#464 fix: kicked user invited again into group,the group info do not changed.
  internal/group/group.go
  internal/group/notification.go
Labels: size/S

#466 fix: rIssue with Asset Uploading for Official Releases in GoReleaser Action v4 - release openim version not auto build
  .goreleaser.yaml
Labels: size/S

#468 fix: conversation and message's sender info change when notification user's info changed.
  internal/conversation_msg/conversation_notification.go
  internal/friend/friend.go
  internal/full/open_im_sdk_full.go
  internal/group/group.go
  internal/user/user.go
  pkg/common/trigger_channel.go
Labels: size/M

#470 feat: support conversation input status and wasm websocket message returns the connection status
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/entering.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/em.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_client.go
  pkg/constant/constant.go
  sdk_struct/sdk_struct.go
  test/t_conversation_msg.go
  test/t_friend_sdk.go
  testv2/init.go
  wasm/event_listener/listener.go
Labels: size/L

#469 fix: conversation and message's sender info change when notification …
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sdk.go
  internal/friend/friend.go
  internal/full/open_im_sdk_full.go
  internal/group/group.go
  internal/user/user.go
  pkg/common/trigger_channel.go
Labels: size/M

#478 fix: remove some code to avoid creating group errors..
  internal/group/sdk.go
  pkg/db/db_interface/databse.go
  pkg/db/super_group_model.go
Labels: size/M

#476 Fix #475
  internal/conversation_msg/sdk.go
  internal/file/upload.go
Labels: size/S

#480 fix: Failure to upload video message content will cause the SDK to crash
  internal/conversation_msg/sdk.go
  internal/file/upload.go
Labels: size/S

#479 fix: remove some code to avoid creating group errors..
  internal/group/sdk.go
  pkg/db/db_interface/databse.go
  pkg/db/super_group_model.go
Labels: size/M

#477 add usercommand and sync and notifiaction for add emoticon
  go.mod
  go.sum
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_notification.go
  internal/friend/friend.go
  internal/friend/sdk.go
  internal/user/convert.go
  internal/user/sync.go
  internal/user/user.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/em.go
  open_im_sdk/friend.go
  open_im_sdk/user.go
  open_im_sdk_callback/callback_client.go
  pkg/constant/constant.go
  pkg/constant/server_api_router.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/model_struct/data_model_struct.go
  pkg/db/user_command.go
  pkg/sdk_params_callback/friend_sdk_struct.go
  test/t_friend_sdk.go
  testv2/config.go
  testv2/init.go
  testv2/user_test.go
  wasm/cmd/main.go
  wasm/event_listener/listener.go
  wasm/indexdb/init.go
  wasm/indexdb/temp_struct/struct.go
  wasm/indexdb/user_command.go
  wasm/wasm_wrapper/wasm_user.go
Labels: size/XL

#489 fix: unread num is negative and optimization of sync conversation when app login or re conn.
  go.mod
  go.sum
  internal/conversation_msg/sync.go
  pkg/common/check.go
  pkg/server_api_params/third_api_struct.go
  test/account.go
Labels: size/L

#488 fix: unread num is negative and optimization of sync conversation when app login or re conn.
  go.mod
  go.sum
  internal/conversation_msg/sync.go
  pkg/common/check.go
  pkg/server_api_params/third_api_struct.go
  test/account.go
Labels: size/L

#492 fix: GroupApplicationRejectedNotification trigger problem
  internal/group/notification.go
Labels: size/S

#491 fix: GroupApplicationRejectedNotification trigger problem
  internal/group/notification.go
Labels: size/S

#503 feat: CheckResourceLoad when Synccall
  open_im_sdk/caller.go
Labels: size/XS

#509 fix: db remove map avoid concurrent login or logout database closed.
  internal/login/init_login.go
  internal/login/sdk.go
  open_im_sdk/userRelated.go
  pkg/db/db_init.go
Labels: size/M

#508 fix: db remove map avoid concurrent login or logout database closed.
  internal/login/init_login.go
  internal/login/sdk.go
  open_im_sdk/caller.go
  open_im_sdk/userRelated.go
  pkg/db/db_init.go
Labels: size/M
