Repository openimsdk/openim-sdk-core, pull requests merged in 2024-07, with the labels that each got.

#564 comment not use SDK core interface
  open_im_sdk/friend.go
  open_im_sdk/group.go
Labels: size/S

#565 fix: token cb update.
  go.mod
  go.sum
  internal/interaction/long_conn_mgr.go
  open_im_sdk/apicb.go
Labels: size/S

#571 fix:optimize login
  internal/interaction/msg_sync.go
  pkg/db/chat_log_model_v3.go
  pkg/db/conversation_model.go
  pkg/db/db_interface/databse.go
Labels: size/L

#570 feat: update wasm feature implement to v3.8
  go.mod
  go.sum
  msgtest/module/manager.go
  msgtest/module/msg_sender.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/userRelated.go
  pkg/db/app_version.go
  pkg/db/db_js.go
  pkg/db/version_sync.go
  testv2/app_version_test.go
  testv2/friend_db_test.go
  testv2/friend_test.go
  testv2/group_db_test.go
  testv2/group_test.go
  testv2/init.go
  testv2/notification_db_test.go
  testv2/version_sync_db_test.go
  wasm/cmd/main.go
  wasm/event_listener/listener.go
  wasm/exec/executor.go
  wasm/indexdb/app_version.go
  wasm/indexdb/chat_log_model.go
  wasm/indexdb/friend_model.go
  wasm/indexdb/group_member_model.go
  wasm/indexdb/group_model.go
  wasm/indexdb/group_request.model.go
  wasm/indexdb/notification_model.go
  wasm/indexdb/version_sync.go
  wasm/wasm_wrapper/wasm_group.go
Labels: size/XL

#576 feat: add function of GetUsersInGroup checks if the provided userIDs …
  internal/group/sdk.go
  open_im_sdk/group.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_group.go
Labels: size/M

#577 fix: update featute implement in wasm
  pkg/db/model_struct/data_model_struct.go
  pkg/db/version_sync.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_friend.go
Labels: size/S

#578 fix: solve multiplatform sync concurrency error.
  internal/conversation_msg/conversation_msg.go
  internal/group/group.go
  internal/group/notification.go
  internal/group/sdk.go
  internal/group/sync2.go
  internal/incrversion/option.go
  internal/user/sync.go
  pkg/db/app_version.go
  pkg/db/db_init.go
  pkg/db/user_model.go
  pkg/db/version_sync.go
Labels: size/M

#579 fix: solve nil pointer in wasm.
  wasm/indexdb/version_sync.go
Labels: size/S

#580 fix: update uncorrect error use.
  wasm/indexdb/version_sync.go
Labels: size/XS

#581 fix: update uncorrect statement.
  pkg/db/group_member_model.go
Labels: size/XS

#582 fix: update condition return args.
  pkg/db/version_sync.go
Labels: size/XS

#583 feat: update pingpongHandler.
  internal/interaction/long_conn_mgr.go
  internal/interaction/long_connection.go
  internal/interaction/ws_default.go
  internal/interaction/ws_js.go
Labels: size/M

#584 fix: update incr sync timing logic when quit group.
  internal/group/sdk.go
Labels: size/S

#585 fix: solve group concurrency issue.
  internal/group/notification.go
  internal/group/sdk.go
Labels: size/XS

#586 fix: solve concurrecy issues in group.
  internal/group/sdk.go
Labels: size/S

#588 feat: implement syncData when App not isBackground.
  internal/conversation_msg/conversation_notification.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
Labels: size/L

#589 refactor: optimize uncorrect structure about pkg and method use.
  internal/friend/friend.go
  internal/friend/notification.go
  internal/friend/sdk.go
  internal/friend/sync.go
  internal/group/sync.go
Labels: size/L

#590 feat: correct concurrecy in friend module.
  internal/friend/friend.go
  internal/friend/notification.go
  internal/friend/sdk.go
Labels: size/S

#591 Main is joind group
  go.mod
  go.sum
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/sdk.go
  internal/conversation_msg/sync.go
  internal/conversation_msg/sync2.go
  internal/friend/sync2.go
  internal/group/group.go
  internal/group/sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/long_connection.go
  internal/interaction/msg_sync.go
  internal/interaction/ws_js.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  pkg/constant/server_api_router.go
  pkg/db/app_version.go
  pkg/db/chat_log_model_v3.go
  pkg/db/conversation_model.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/model_struct/data_model_struct.go
Labels: size/XL

#594 feat: implement get existed table name in sql master
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/table_master.go
  wasm/indexdb/conversation_model.go
  wasm/indexdb/table_master.go
Labels: size/M

#595 fix: update TriggerCmdSyncData args.
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
Labels: size/XS

#554 fix: upload failure due to time expiration
  internal/file/upload.go
Labels: size/M

#555 fix: upload failure due to time expiration
  internal/file/upload.go
Labels: size/M

#597 fix: change limit int type avoid overflow and group member sorted.
  internal/conversation_msg/conversation_msg.go
  internal/friend/friend.go
  internal/interaction/long_conn_mgr.go
  internal/util/post.go
  pkg/datafetcher/datafetcher.go
  pkg/syncer/syncer.go
Labels: size/M

#598 refactor: split sync data and notification cmd and add some heartbeat log.
  internal/conversation_msg/conversation_notification.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  sdk_struct/sdk_struct.go
Labels: size/M

#601 fix: sdk logout due to client kick online, incr sync data trigger full id.
  .DS_Store
  go.mod
  go.sum
  internal/friend/sync2.go
  internal/group/notification.go
  internal/group/sync2.go
  internal/incrversion/option.go
  internal/interaction/long_conn_mgr.go
  open_im_sdk/userRelated.go
Labels: size/L

#600 feat: log support system type and ex
  internal/third/log.go
  open_im_sdk/third.go
  testv2/third_test.go
Labels: size/M

#602 feat: implement checkConversation seq.
  internal/interaction/msg_sync.go
  pkg/db/chat_log_model.go
  pkg/db/db_interface/databse.go
  wasm/indexdb/chat_log_model.go
Labels: size/S

#599 feat: update method to adapted the corresponding parms.
  internal/group/sync2.go
Labels: size/S

#607 feat: protocol
  sdk_struct/sdk_struct.go
Labels: size/XS

#606 feat: online status subscription
  internal/conversation_msg/conversation_notification.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/online.go
  internal/interaction/subscription.go
  internal/interaction/subscription_test.go
  internal/interaction/ws_resp_asyn.go
  internal/user/sdk.go
  internal/user/sync.go
  internal/user/user.go
  msgtest/module/msg_sender.go
  open_im_sdk/online.go
  open_im_sdk/user.go
  open_im_sdk/userRelated.go
  pkg/constant/constant.go
  testv2/config.go
  testv2/empty_test.go
  testv2/sync_test.go
  testv2/third_test.go
  testv2/user_test.go
Labels: size/XL

#608 feat: update msg Sync by Reinstalled trigger const.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/message_check.go
  pkg/constant/constant.go
Labels: size/L

#604 Fix logs upload
  internal/third/log.go
  internal/third/third.go
  testv2/third_test.go
Labels: size/M

#609 Fix syncmsg
  go.mod
  go.sum
  internal/interaction/msg_sync.go
  pkg/common/trigger_channel.go
  sdk_struct/sdk_struct.go
Labels: size/L

#610 fix: conversation list will disappear when conversation version table has been deleted in server.
  .DS_Store
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/sync2.go
Labels: size/S

#611 fix: update loss contents.
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  pkg/common/trigger_channel.go
  pkg/db/chat_log_model.go
Labels: size/S

#612 fix: remove uncorrect use ctx and conditdion.
  internal/conversation_msg/conversation_msg.go
  internal/interaction/msg_sync.go
Labels: size/S

#614 fix uncorrect progress add.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
Labels: size/XS

#615 feat: update progress logic.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/interaction/msg_sync.go
Labels: size/M

#617 feat: test
  integration_test/README.md
  integration_test/internal/manager/group_manager.go
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/relation_manager.go
  integration_test/internal/manager/user_manager.go
  integration_test/internal/pkg/initialization/config.go
  integration_test/internal/pkg/initialization/flag.go
  integration_test/internal/pkg/sdk_user_simulator/listener.go
  integration_test/internal/pkg/sdk_user_simulator/user.go
  integration_test/internal/pkg/utils/group.go
  integration_test/internal/pkg/utils/user.go
  integration_test/internal/process/checker/group.go
  integration_test/internal/process/checker/model.go
  integration_test/internal/process/v1.go
  integration_test/internal/sdk/group.go
  integration_test/internal/sdk/sdk.go
  integration_test/internal/vars/cmd.go
  integration_test/internal/vars/config.go
  integration_test/internal/vars/group.go
  integration_test/internal/vars/limit.go
  integration_test/internal/vars/user.go
  integration_test/main.go
Labels: size/XXL

#616 refactor: remove unuse sdk version field.
  internal/third/log.go
  internal/third/third.go
  open_im_sdk/init_login.go
  open_im_sdk/userRelated.go
  pkg/constant/constant.go
Labels: size/M

#619 test: support parameter passing and function calling
  go.mod
  go.sum
  integration_test/internal/config/config.go
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/user_manager.go
  integration_test/internal/pkg/initialization/config.go
  integration_test/internal/pkg/initialization/flag.go
  integration_test/internal/pkg/initialization/sdk.go
  integration_test/internal/pkg/sdk_user_simulator/user.go
  integration_test/internal/process/checker/common.go
  integration_test/internal/process/checker/group.go
  integration_test/internal/process/v1.go
  integration_test/internal/vars/cmd.go
  integration_test/internal/vars/config.go
  integration_test/main.go
  open_im_sdk/init_login.go
  open_im_sdk/userRelated.go
  test/account.go
Labels: size/L

#620 fix: remove unnecesarry condition in ws.
  internal/interaction/ws_default.go
  internal/interaction/ws_js.go
  open_im_sdk/init_login.go
  pkg/sdkerrs/predefine.go
Labels: size/S

#621 feat: log can add line and delete old logs
  internal/third/log.go
  open_im_sdk/third.go
Labels: size/L

#623 Fix test
  go.mod
  go.sum
  integration_test/internal/config/config.go
  integration_test/internal/config/limit.go
  integration_test/internal/manager/group_manager.go
  integration_test/internal/manager/manager.go
  integration_test/internal/manager/relation_manager.go
  integration_test/internal/manager/user_manager.go
  integration_test/internal/pkg/initialization/flag.go
  integration_test/internal/pkg/initialization/log.go
  integration_test/internal/pkg/initialization/sdk.go
  integration_test/internal/pkg/sdk_user_simulator/user.go
  integration_test/internal/process/checker/group.go
  integration_test/internal/sdk/group.go
  integration_test/internal/vars/cmd.go
  integration_test/internal/vars/limit.go
  integration_test/internal/vars/user.go
  integration_test/main.go
  open_im_sdk/init_login.go
  open_im_sdk/userRelated.go
Labels: size/L

#622 refactor: optimize conversation notification structure.
  cmd/gordon_main.go
  cmd/sk_main.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversation_notification.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/sdk.go
  internal/group/group.go
  internal/group/notification.go
  internal/group/sdk.go
  internal/interaction/long_conn_mgr.go
  open_im_sdk/group.go
  pkg/common/check.go
  pkg/common/wrap_error.go
  pkg/constant/constant.go
  pkg/constant/error.go
  pkg/constant/server_error.go
  pkg/db/group_member_model.go
  pkg/db/super_group_chat_log_model.go
  pkg/utils/utils.go
  test/online.go
  test/reliability.go
  test/sendMessage.go
  test/t_conversation_msg.go
  test/t_group_sdk.go
  test/t_signaling.go
  test/work_group_create.go
  test/work_moments.go
  testv2/conversation_test.go
  testv2/friend_test.go
  testv2/group_test.go
  testv2/init.go
  testv2/signaling_test.go
  testv2/sync_test.go
  testv2/third_test.go
  testv2/user_test.go
  testv2/work_moment_test.go
  wasm/cmd/main.go
  wasm/cmd/static/wasm_exec.js
  wasm/event_listener/caller.go
  wasm/indexdb/chat_log_model.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
  wasm/wasm_wrapper/wasm_init_login.go
Labels: size/XXL

#625 fix: abnormal session, the session unread count is not 0, according to the message the unread count should be 0, can not be eliminated
  internal/conversation_msg/read_drawing.go
Labels: size/S

#627 fix: conversation will deadlock when sync data logging.
  internal/conversation_msg/conversation_notification.go
  internal/interaction/msg_sync.go
Labels: size/XS

#628 fix: set scanner buffer
  internal/third/log.go
Labels: size/XS
