Repository openimsdk/openim-sdk-core, pull requests merged in 2025-06, with the labels that each got.

#960 fix: refactor friend request and group request handling by removing l…
  go.mod
  go.sum
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/notification.go
  internal/conversation_msg/skipList.go
  internal/conversation_msg/sync.go
  internal/group/api.go
  internal/group/cache.go
  internal/group/conversion.go
  internal/group/filter.go
  internal/group/full_sync.go
  internal/group/group.go
  internal/group/incremental_sync.go
  internal/group/notification.go
  internal/group/server_api.go
  internal/interaction/msg_sync.go
  internal/relation/api.go
  internal/relation/conversion.go
  internal/relation/notification.go
  internal/relation/relation.go
  internal/relation/server_api.go
  internal/relation/sync.go
  internal/user/full_sync.go
  internal/user/user.go
  open_im_sdk/group.go
  open_im_sdk/init_login.go
  open_im_sdk/relation.go
  open_im_sdk/userRelated.go
  pkg/api/api.go
  pkg/common/EventQueue.go
  pkg/common/EventQueue_test.go
  pkg/common/priorityQueue.go
  pkg/common/priorityQueue_test.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  pkg/db/conversation_model.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/friend_request_model.go
  pkg/db/group_request_model.go
  pkg/sdk_params_callback/friend_sdk_struct.go
  pkg/sdk_params_callback/group_sdk_struct.go
  pkg/sort_conversation/sort_conversation.go
  pkg/utils/utils.go
  wasm/cmd/main.go
  wasm/indexdb/conversation_model.go
  wasm/indexdb/friend_request_model.go
  wasm/indexdb/group_request.model.go
  wasm/indexdb/init.go
  wasm/wasm_wrapper/wasm_friend.go
  wasm/wasm_wrapper/wasm_group.go
Labels: size/XXL

#969 fix: Can`t send notification in import_friend
  internal/relation/notification.go
  open_im_sdk/userRelated.go
Labels: size/XS

#972 fix: modify the app's foreground and background status switch, first modify it locally to prevent the SDK from triggering offline messages and not triggering the normal newMessage.
  open_im_sdk/userRelated.go
Labels: size/XS

#975 docs: create gomobile android ios setup EN docs.
  docs/gomobile-android-ios-setup-cn.md
  docs/gomobile-android-ios-setup.md
Labels: size/L
