Repository openimsdk/openim-sdk-core, pull requests merged in 2025-03, with the labels that each got.

#871 fix: sync self conversation's avatar when user's info changed.
  internal/user/user.go
Labels: size/XS

#868 fix: add a manually triggered IM message synchronization mechanism to…
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/revoke.go
  internal/interaction/msg_sync.go
  open_im_sdk/userRelated.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  proto/conversation.pb.go
  proto/event.pb.go
  proto/ffi.pb.go
  proto/ffi.proto
  proto/init.pb.go
  proto/msggateway.pb.go
Labels: size/XXL

#874 fix: directly deduplicate the messages pulled from the server.
  internal/conversation_msg/message_check.go
Labels: size/S

#873 fix: directly deduplicate the messages pulled from the server.
  internal/conversation_msg/message_check.go
Labels: size/S

#881 fix: get group member info maybe failed.
  internal/conversation_msg/revoke.go
Labels: size/S

#880 fix: get group member info maybe failed.
  internal/conversation_msg/revoke.go
Labels: size/S

#884 fix: change secret && cicd modify secret
  .github/workflows/go-build-test.yml
  integration_test/internal/config/config.go
Labels: size/S

#888 feat: sdk not init and not login code
  open_im_sdk/userRelated.go
  pkg/sdkerrs/code.go
Labels: size/XS

#893 fix: add mutex for get conversation prevent concurrent insert convers…
  internal/conversation_msg/api.go
Labels: size/XS

#894 fix: add mutex for get conversation prevent concurrent insert convers…
  internal/conversation_msg/api.go
Labels: size/XS
