Repository openimsdk/openim-sdk-core, pull requests merged in 2025-04, with the labels that each got.

#895 feat: caching for special users of the SDK to prevent cache breakdown…
  internal/conversation_msg/conversion.go
  internal/conversation_msg/message_check.go
  internal/group/cache.go
  internal/interaction/long_conn_mgr.go
  msgtest/module/msg_sender.go
  open_im_sdk/userRelated.go
  pkg/cache/user_cache.go
  pkg/constant/constant.go
  sdk_struct/sdk_struct.go
Labels: size/L

#900 feat: CheckLocalGroupFullSync & CheckGroupMemberFullSync
  internal/group/api.go
  open_im_sdk/group.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_group.go
Labels: size/M

#902 refactor: revert createMsg interface.
  internal/conversation_msg/api.go
  internal/conversation_msg/create_message.go
  open_im_sdk/conversation_msg.go
  test/config.go
  test/conversation_test.go
  test/create_msg_test.go
  wasm/cmd/main.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/XL

#912 refactor: improve workflows by merge and release
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  .github/workflows/merge-from-milestone.yml
  .github/workflows/update-version-file-on-release.yml
Labels: size/L

#916 refactor: change conversation channel to priority queue and adjust strategy of message sync.
  go.mod
  go.sum
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/conversion.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/notification.go
  internal/conversation_msg/read_drawing.go
  internal/conversation_msg/revoke.go
  internal/conversation_msg/server_api.go
  internal/conversation_msg/skipList.go
  internal/conversation_msg/stream_msg.go
  internal/conversation_msg/sync.go
  internal/group/api.go
  internal/group/cache.go
  internal/group/full_sync.go
  internal/group/group.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/msg_sync.go
  internal/interaction/ws_resp_asyn.go
  internal/relation/relation.go
  internal/user/api.go
  internal/user/user.go
  msgtest/config.go
  msgtest/module/msg_sender.go
  open_im_sdk/apicb.go
  open_im_sdk/caller.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/init_login.go
  open_im_sdk/user.go
  open_im_sdk/userRelated.go
  open_im_sdk_callback/callback_client.go
  pkg/api/api.go
  pkg/cache/user_cache.go
  pkg/cliconf/client_config.go
  pkg/cliconf/global.go
  pkg/common/EventQueue.go
  pkg/common/EventQueue_test.go
  pkg/common/cmd.go
  pkg/common/priorityQueue.go
  pkg/common/priorityQueue_test.go
  pkg/common/trigger_channel.go
  pkg/constant/constant.go
  pkg/db/conversation_model.go
  pkg/sort_conversation/sort_conversation.go
  sdk_struct/sdk_struct.go
  test/config.go
  test/conversation_test.go
  test/empty_test.go
  test/init.go
  test/listener.go
Labels: size/XXL

#917 merge: merge code into v3.8.4 from main.
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/workflows/auto-invite-comment.yml
  .github/workflows/delete-users-invalid-comments.yml
  .github/workflows/update-version-file-on-release.yml
  .gitignore
  CONTRIBUTING.md
  LICENSE
  README.md
  README_zh-CN.md
  docs/gomobile-android-ios-setup-cn.md
  go.mod
  integration_test/internal/pkg/sdk_user_simulator/listener.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/create_message.go
  internal/conversation_msg/delete.go
  internal/conversation_msg/skipList.go
  internal/group/api.go
  internal/relation/api.go
  msgtest/sdk_user_simulator/listener.go
  open_im_sdk/caller.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/em.go
  open_im_sdk_callback/callback_client.go
  pkg/ccontext/context.go
  pkg/db/chat_log_model.go
  pkg/db/db_interface/databse.go
  scripts/template/footer.md.tmpl
  test/listener.go
  wasm/cmd/main.go
  wasm/event_listener/listener.go
  wasm/indexdb/chat_log_model.go
  wasm/wasm_wrapper/wasm_conversation_msg.go
Labels: size/XXL

#918 fix: solve incorrect args in CreateMsg method.
  open_im_sdk/conversation_msg.go
Labels: size/S

#923 fix: use a custom close code for javascript websocket active disconnection to prevent close failures, according to the WebSocket RFC documentation.
  go.mod
  go.sum
  internal/interaction/long_conn_mgr.go
  internal/interaction/ws_js.go
Labels: size/S

#922 fix: recycle javascript promise function manually to prevent memory l…
  wasm/event_listener/callback_writer.go
Labels: size/S

#927 feat: optimize notification triggering
  internal/conversation_msg/notification.go
  internal/group/notification.go
  internal/relation/notification.go
  internal/user/notification.go
Labels: size/M

#929 fix: SyncLoginUserInfo
  internal/user/full_sync.go
Labels: size/XS

#930 fix: SyncLoginUserInfo
  internal/user/full_sync.go
Labels: size/XS

#933 feat: wasm support application layer ping
  internal/interaction/ws_js.go
Labels: size/L

#935 fix: failure to clear @ tags in conversations, group member synchronization errors, and friend list synchronization anomalies,due to concurrency.
  go.mod
  go.sum
  internal/conversation_msg/incremental_sync.go
  internal/conversation_msg/notification.go
  internal/group/full_sync.go
  internal/group/incremental_sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/ws_js.go
  internal/relation/incremental_sync.go
  internal/relation/sync.go
  internal/user/full_sync.go
  open_im_sdk/apicb.go
  open_im_sdk/userRelated.go
  wasm/event_listener/callback_writer.go
Labels: size/L

#937 fix: failure to clear @ tags in conversations, group member synchronization errors, and friend list synchronization anomalies,due to concurrency.
  go.mod
  go.sum
  internal/conversation_msg/incremental_sync.go
  internal/conversation_msg/notification.go
  internal/group/full_sync.go
  internal/group/incremental_sync.go
  internal/interaction/long_conn_mgr.go
  internal/interaction/ws_js.go
  internal/relation/incremental_sync.go
  internal/relation/sync.go
  open_im_sdk/apicb.go
  open_im_sdk/conversation_msg.go
  open_im_sdk/userRelated.go
  wasm/event_listener/callback_writer.go
Labels: size/L

#939 feat: Add StopGoroutineOnBackground whether to stop goroutines when s…
  internal/interaction/long_conn_mgr.go
  msgtest/module/msg_sender.go
  open_im_sdk/userRelated.go
  sdk_struct/sdk_struct.go
Labels: size/M

#940 V3.8.4 watch dog
  internal/interaction/long_conn_mgr.go
  msgtest/module/msg_sender.go
  open_im_sdk/userRelated.go
  sdk_struct/sdk_struct.go
Labels: size/M
