Repository openimsdk/openim-sdk-core, pull requests merged in 2025-07, with the labels that each got.

#976 fix: solve lose uid kv when incr Sync.
  pkg/syncer/version_synchronizer.go
Labels: size/M

#983 feat: create sdk releaser workflows in pre-release-v3.8.4 branch.
  .github/workflows/release.yml
  .github/workflows/sdk-releaser.yml
Labels: size/L

#980 feat: Implement sdk releaser workflows
  .github/workflows/release.yml
  .github/workflows/sdk-releaser.yml
Labels: size/L

#985 fix: update version file in sdk releaser in v3.8.3-patch branch.
  .github/workflows/sdk-releaser.yml
Labels: size/S

#984 fix: update version file in sdk releaser in pre-release-v3.8.4
  .github/workflows/sdk-releaser.yml
Labels: size/S

#990 fix: remove new line in update version file in pre-release-v3.8.4.
  .github/workflows/update-version-file-on-release.yml
Labels: size/M

#995 fix: update wasm archive have wasm_exec.js in v3.8.3-patch branch.
  .github/workflows/sdk-releaser.yml
  wasm/cmd/Makefile
Labels: size/S

#993 fix: update wasm archive have wasm_exec.js.
  .github/workflows/sdk-releaser.yml
  wasm/cmd/Makefile
Labels: size/S

#992 fix: the sent message is modified by webhook and cannot be synchronized
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/entering.go
Labels: size/M

#1000 fix: solve incorrect distinct in IncrSync and remove goroutine in syncAndTriggerReinstallMsgs func in v3.8.3-patch.
  internal/interaction/msg_sync.go
  open_im_sdk/userRelated.go
  pkg/syncer/version_synchronizer.go
Labels: size/M

#1009 fix: add safe submodule in workflows in v3.8.3-patch.
  .github/workflows/update-version-file-on-release.yml
Labels: size/S

#1013 fix: set correct resp in sendMsgToServer
  internal/conversation_msg/api.go
Labels: size/S
