Repository openimsdk/openim-sdk-core, pull requests merged in 2025-02, with the labels that each got.

#845 fix: server downtime and abnormal message handling may lead to message duplication, and the history retrieval interface might miss messages when the timestamps are the same.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/message_check_test.go
  internal/conversation_msg/revoke.go
  pkg/db/chat_log_model.go
  pkg/db/db_interface/databse.go
  wasm/indexdb/chat_log_model.go
Labels: size/L

#852 optimize the freeze caused by too many friends and group applications
  internal/group/full_sync.go
  internal/group/group.go
  internal/relation/relation.go
  internal/relation/sync.go
Labels: size/M

#850 fix: add random prefix to remove duplicate messages.
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
Labels: size/S

#844 fix: GetConversationIDBySessionType 返回的字符串带转义符
  open_im_sdk/conversation_msg.go
Labels: size/XS

#841 fix: refine exception message handling to prevent duplicate messages …
  internal/conversation_msg/api.go
  internal/conversation_msg/conversation.go
  internal/conversation_msg/conversation_msg.go
  internal/conversation_msg/message_check.go
  internal/conversation_msg/message_check_test.go
  internal/conversation_msg/revoke.go
  pkg/db/chat_log_model.go
  pkg/db/chat_log_reaction_extension_model.go
  pkg/db/db_init.go
  pkg/db/db_interface/databse.go
  pkg/db/db_js.go
  pkg/db/err_chat_log_model.go
  pkg/db/model_struct/data_model_struct.go
  pkg/db/super_group_chat_log_model.go
  test/conversation_test.go
  wasm/indexdb/chat_log_model.go
  wasm/indexdb/chat_log_reaction_extension_model.go
  wasm/indexdb/init.go
Labels: size/XXL

#853 optimize the freeze caused by too many friends and group applications && fix: GetConversationIDBySessionType returns a string with escape characters.
  internal/conversation_msg/conversation.go
  internal/group/full_sync.go
  internal/group/group.go
  internal/relation/relation.go
  internal/relation/sync.go
  open_im_sdk/conversation_msg.go
Labels: size/M

#854 docs: readme doc update and add doc for gomobile compile sdk core.
  README.md
  README_zh-CN.md
  docs/gomobile-android-ios-setup-cn.md
Labels: size/L

#855 build: fix merge failed when conflict.
  .github/workflows/merge-from-milestone.yml
Labels: size/S

#857 fix: modify the historical message retrieval interface to address the message gap problem caused by server crashes or redis seq cache expired.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/revoke.go
  pkg/db/chat_log_model.go
  pkg/db/db_interface/databse.go
  test/conversation_test.go
  wasm/indexdb/chat_log_model.go
Labels: size/M

#856 fix: modify the historical message retrieval interface to address the message gap problem caused by server crashes or redis seq cache expired.
  internal/conversation_msg/conversation.go
  internal/conversation_msg/revoke.go
  pkg/db/chat_log_model.go
  pkg/db/db_interface/databse.go
  test/conversation_test.go
  wasm/indexdb/chat_log_model.go
Labels: size/M

#860 chore: update slack link in repo.
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/workflows/auto-invite-comment.yml
  CONTRIBUTING.md
  README.md
  README_zh-CN.md
  scripts/template/footer.md.tmpl
Labels: size/L
